version: '3.8'
services:
  file_storage:
    build: .
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/file_storage
    ports:
      - "8080:8080"
    restart: always

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=file_storage
